staticafi/symbiotic

build.sh
I've been testing LLVM download in build phase a bit and achieved considerably better results using curl for downloading then with wget. The curl command I suggest to use is `curl -LRO $URL`.
Those flags cause curl to:
- re-downloaded partially downloaded archive replacing the partial download
- cancel download if the archive exists and is up to date
This PR should fix #64 .
Signed-off-by: Tomas Jasek <tomsik68@gmail.com>
=> build: use curl instead of wget for downloads

build.sh
On my Fedora, STP gets installed to `install/lib64`, but the script sets `LD_LIBRARY_PATH` to `install/lib`.
This should fix it.
Alternatively, you could stop fighting individual build scripts, let them install to the arch-specific libdir and use `LD_LIBRARY_PATH='install/$LIB'` (`ld.so` would resolve `$LIB` to the arch-specific name).
=> build.sh: Set libdir for stp

lib/symbioticpy/symbiotic/symbiotic.py, lib/symbioticpy/symbiotic/utils/utils.py
From clang's version 4.0.1 we want to use -force-lifetime-markers
option for memsafety instrumentation.
=> Check clang version for memsafety

.travis.yml, system-build.sh, tests/run_tests.sh
This PR adds support for Travis CI. Symbiotic is built with LLVM versions 4.0 and 5.0. Because of build time limit, it needs to use `system-build.sh` instead of `build.sh` (because LLVM building takes too long). After building Symbiotic, regression tests are also run, but their results are not taken into account. That means, if compilation is successful but tests fail, the CI passes. We can still change this by inspecting `results.txt`.
I had to modify `system-build.sh` to copy clang's built-in headers to `$LLVM_PREFIX/lib/` (see https://clang.llvm.org/docs/LibTooling.html#builtin-includes for more information about that).
I also had to modify `run_tests.sh` to use Symbiotic in the `install` folder, because the version in scripts folder is unable to find the LLVM prefix directory when …
=> Add continuous integration support

lib/symbioticpy/symbiotic/options.py
By default witness file was generated into the symbiotic install directory.
This caused Permission Error when symbiotic was installed into /opt where
it didn't have permission to write.
=> Generate witness file in current working dir

build.sh
This allows running `build.sh` even if z3 is already built.
=> build: check if z3 directory exists before cloning

lib/symbioticpy/symbiotic/options.py
By adding a missing '=' in options parsing.
Previously, usage of `--no-link` failed.
For example:
```
ERROR: option --no-link must not have an argument
```
=> Allow usage of parameter '--no-link'

lib/symbioticpy/symbiotic/verifier.py
benchexec modules expect output lines to be a list of strings, while
watch returns list of bytes objects.
this change allows benchexec modules to be used with Symbiotic without
modifications.
Here is a traceback of an error this PR addresses:
```
|> /var/tmp/xjasek/predatorhp-llvm/predatorHP.py --propertyfile /var/tmp/xjasek/build_archive/symbiotic-predatorhp/install/properties/valid-memsafety.prp /tmp/symbiotic-c6fbzr87/code-pr-inst-pr-opt-pr-opt-pr.bc --compiler-options=-m32
UNKNOWN
INFO: Verification time: 0.2759096622467041
Traceback (most recent call last):
File "./symbiotic", line 129, in <module>
res = symbiotic.run()
File "/var/tmp/xjasek/build_archive/symbiotic-predatorhp/install/lib/symbioticpy/symbiotic/symbiotic.py", line 151, in run
return self._run_symbiotic()
File …
```
=> verifier.py: convert output lines to strings

lib/symbioticpy/symbiotic/utils/process.py
ProcessRunner may discard some parts of a sub-process output whenever
the sub-process writes of the pipe and subsequently exits in the exact
moment between the lines below.
```python
line = ProcessRunner.current_process.stdout.readline()
if line == b'' and ProcessRunner.current_process.poll() is not None:
```
This behaviour could be observed when multiple instances of Symbiotic
were launched in parallel.
Fixes #138.
=> utils/process.py: Fix possible discarding of subprocess output

build.sh, scripts/precompile_bitcode_files.sh, scripts/symbiotic, system-build.sh
- Allow a custom `$PREFIX` path.
- Set rpath for `dg` and `sbt-slicer` so that they can be run independently from Symbiotic.
- Use symbolic links for system LLVM tools.
- Check whether Symbiotic is executed from a symbolic link.
EDIT: Some changes moved to #151.
=> Minor fixes

lib/symbioticpy/symbiotic/targets/klee.py
Fixes:
```
$ symbiotic --full-instrumentation empty_main.c
...
File "/opt/symbiotic/lib/symbioticpy/symbiotic/verifier.py", line 75, in _run_verifier
res = self._tool.determine_result(returncode, 0,
File "/opt/symbiotic/lib/symbioticpy/symbiotic/targets/klee.py", line 390, in determine_result
return self.FullInstr.determine_result(returncode, returnsignal, output, isTimeout)
File "/opt/symbiotic/lib/symbioticpy/symbiotic/targets/klee.py", line 161, in determine_result
fnd = self._parse_klee_output_line(line.decode('ascii'))
AttributeError: 'str' object has no attribute 'decode'
```
=> targets/klee.py: Fix --full-instrumentation option

lib/symbioticpy/symbiotic/options.py, lib/symbioticpy/symbiotic/targets/klee.py
This option specifies a comma-separated list of arguments to be passed
to the main function of the verified program.
=> options.py: Add support for --argv option

system-build.sh
In this case the version string ends with an additional "git" suffix.
=> system-build.sh: Fix build with devel versions of LLVM

transforms/InstrumentNontermination.cpp, transforms/MakeNondet.cpp, transforms/PrepareOverflows.cpp, transforms/RemoveInfiniteLoops.cpp, transforms/Unrolling.cpp
This PR fixes warnings, that were uncovered by #152 as the previous usage of LLVM CMake machinery suppressed them.
The only warning that still persists is the following one. If you tell me the expected return value, I can can fix it additionally.
``` 
InstrumentNontermination.cpp: In member function ‘bool InstrumentNontermination::instrumentEmptyLoop(llvm::Loop*)’:
InstrumentNontermination.cpp:394:1: warning: no return statement in function returning non-void [-Wreturn-type]
394 | }
| ^
```
=> Fix transforms warnings

lib/symbioticpy/symbiotic/targets/tool.py, lib/symbioticpy/symbiotic/transform.py
When Symbiotic checks for `--prp no-overflow`, no slicing criterion is supplied which results in an empty program. The slicer is started as `|> timeout 300 sbt-slicer -c  -pta fi /tmp/symbiotic-nhs2l7nz/code-pr-pr-inst-opt.bc` .
This commit adds `-c __assert_fail` as the instrumentation functions use `assert(/* no overflow occured */);`.
=> tool.py: set slicing crit for overflow prp

transforms/DeleteUndefined.cpp, transforms/InitializeUninitialized.cpp, transforms/InstrumentNontermination.cpp, transforms/MakeNondet.cpp
Unfortunately, the previous patch regarding the instruction constructors (2442de5bd0c5d52714f13814d6a2ac031130c897), that I made, crashes with LLVM 11 (older releases are fine). It turned out that the instruction alignment now must be either deduced from the target `BasicBlock` or supplied explicitly.
Sorry for the hassle. I have tested this patch with LLVM 9-11.
=> transforms-llvm11: Fix calls to instruction constructors

lib/symbioticpy/symbiotic/transform.py, transforms/CloneMetadata.cpp
* Supported: LLVM 12 final
* Changes so far:
*  transforms: Replace `DebugLoc::get` with `DILocation::get` in `CloneMetadata`
*  transforms.py: Implement optimization name selection based on used LLVM version
=> transforms: Support LLVM 12

scripts/symbiotic
This is very useful for automated processing of the results so that users
know how to reproduce it afterwards from the report itself.
=> symbiotic: Print sys.argv contents to the standard output in debug mode

system-build.sh
Fixes the following issue:
```console
$ git clean -dfx
$ git clean submodule foreach git clean -dfx
$ ./system-build
...
CMake Error at src/CMakeLists.txt:23 (add_executable):
Cannot find source file:
jsoncpp.cpp
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
CMake Error at src/CMakeLists.txt:23 (add_executable):
No SOURCES given to target: sbt-instr
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
=> system-build.sh: recopy the amalgamated jsoncpp sources if needed

.github/workflows/linux.yml, lib/symbioticpy/symbiotic/environment.py, tests/run_tests.sh
Use symbiotic's `--dump-env-cmd` to populate the `PATH` environment variable.  Note that using the following construct is intentional so that `set -e` is honoured:
```bash
ENV_CMD="$(symbiotic --dump-env-cmd)"
eval "$ENV_CMD"
```
as can be seen here:
```console
$ bash -xc 'set -e; eval "$(false)"; echo what?'
+ set -e
++ false
+ eval ''
+ echo 'what?'
what?
$ echo $?
0
$ bash -xc 'set -e; ENV_CMD="$(false)"; eval "$ENV_CMD"; echo what?'
+ set -e
++ false
+ ENV_CMD=
$ echo $?
1
```
EDIT: typo
=> tests/run_tests.sh: Remove hack to get path to LLVM binariers

.gitmodules
Support for `git://` was removed by GitHub.
Related: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Fixes:
```
Cloning into '/home/lukas/rpm-symbiotic/srpm/symbiotic/sbt-slicer'...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/staticafi/sbt-slicer' into submodule path '/home/lukas/rpm-symbiotic/srpm/symbiotic/sbt-slicer' failed
Failed to clone 'sbt-slicer'. Retry scheduled
```
=> gitmodules: Update `sbt-slicer` URL to use `https`

.github/workflows/linux.yml
The default branch is now called `main`.
=> CI: rename `master` to `main`

.github/workflows/linux.yml, build.sh, lib/symbioticpy/symbiotic/environment.py, system-build.sh
This is a collection of various fixes for CI and from #231 and #236 that can be merged independently.
=> Various build and CI fixes 
